version: '3.3'

services:
  app:
    build:
      args:
        user: odko
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: dental-img
    container_name: dental-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - dentalNetwork

  nginx:
    image: nginx:1.17-alpine
    container_name: dental-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - dentalNetwork

  db:
    image: mysql
    restart: always
    container_name: dental-db
    environment:
      MYSQL_DATABASE: 'monfamily'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - dentalNetwork
    volumes:
      - dental_db:/var/lib/mysql

volumes:
  dental_db : 

networks:
  dentalNetwork:
    driver: bridge
